# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context_Slice',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('slice_method', models.CharField(choices=[('NE', 'certain name entities'), ('RK', 'rank entities by their freqencies'), ('CL', 'adjacency matrix of documents that are close - share many name entities'), ('FR', 'adjacency matrix of documents that are far - share few name entities')], default='NE', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('docID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('docDate', models.DateField(null=True)),
                ('docSource', models.CharField(max_length=20, null=True)),
                ('docText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document_Entity',
            fields=[
                ('pair_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('occurence', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step3.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('importance', models.DecimalField(choices=[(1, 'Not Important At All'), (2, 'Of Little Importance'), (3, 'Of Average Importance'), (4, 'Very Important'), (5, 'Absolutely Important')], decimal_places=0, default=3, max_digits=1)),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Name_Entity',
            fields=[
                ('entity_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('entity_category', models.CharField(choices=[('Person', 'Person'), ('Location', 'Location'), ('Organization', 'Organization'), ('Money', 'Money'), ('Misc', 'Misc'), ('Phone', 'Phone'), ('Interesting', 'Interesting'), ('Date', 'Date')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.DateTimeField()),
                ('logout', models.DateTimeField()),
                ('context_slice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='step3.Context_Slice')),
            ],
        ),
        migrations.AddField(
            model_name='friends',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='step3.User'),
        ),
        migrations.AddField(
            model_name='friends',
            name='entity_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_ID', to='step3.Name_Entity'),
        ),
        migrations.AddField(
            model_name='friends',
            name='friend_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend_with', to='step3.Name_Entity'),
        ),
        migrations.AddField(
            model_name='document_entity',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step3.Name_Entity'),
        ),
        migrations.AddField(
            model_name='context_slice',
            name='documents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step3.Document'),
        ),
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together=set([('entity_ID', 'friend_with')]),
        ),
    ]
